# Goal
string action  # 'read' 'write' 'single' or 'multi'
uint8[12] epc  # EPC of the tag to be selected
bool tag_select  # whether to select a specific tag or select a default tag
uint8[16] write_data  # data to be written to the selected tag
---
# Result
uint8[16] read_data  # data read from the selected tag
uint8[12] read_epc  # EPC of the selected tag after read operation
bool response  # Response of the operation True = Success False = Fail
uint8[12] write_epc  # EPC of the selected tag after write operation
uint8[12] single_inventory_epc  # default EPC of one of the detected tags after a single poll operation
uint8[60] multi_inventory_epc  # default EPC of the detected tags after a multi poll operation
int64 multi_epc_size # size of the EPC data array after a multi poll operation
---
# Feedback
string progress